# Generated by Django 4.2.4 on 2023-11-04 14:55

import cdn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.ImageField(upload_to=cdn.models.ProfilePicture.image_name)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
